language: python
sudo: false
python:
    - "2.6"
    - "2.7"
install: 
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
script:
    python manage.py test
after_success:
    coveralls
