# Generated by Django 2.2.12 on 2020-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0014_auto_20160504_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
