# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:22
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regcore', '0014_auto_20160504_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('combined_text', models.TextField()),
                ('combined_titles', models.TextField()),
                ('root_title', models.TextField()),
                ('search_vector',
                    django.contrib.postgres.search.SearchVectorField()),
                ('document', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='regcore.Document')),
            ],
        ),
    ]
