# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore_pgsql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentindex',
            name='doc_root',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
